### ISSUE TITLE
site not reachable

### ISSUE THREAD

**Issue by lbehm** [bauhaus/KATALOG#1]
Your website [katalog.bau-ha.us](https://katalog.bau-ha.us/) is not reachable, because of a misconfigured web server.

About every link pointing to a *.bau-ha.us subdomain that can be found on the index page of https://bau-ha.us/ is affected.

Couldn't find contact details on that page. That's why I try to reach out this way.

Greetings

**Comment by eins78** [comment]
thanks for the report, but this is not an active project.
